# Movies longer than 100 minutes

PREFIX ex:      <http://example.org/vocabulary/>
PREFIX schema:  <http://schema.org/>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>

SELECT ?movie ?title (xsd:integer(?mins) AS ?durationMinutes)
WHERE {
  ?movie a schema:Movie ;
         schema:name ?title ;
         ex:durationMinutes ?mins .

  FILTER(xsd:integer(?mins) > 100)
}
ORDER BY DESC(xsd:integer(?mins)) ?title
